@url = http://localhost:8080

### "gameName"/?game= can be bulletspeel or cordel

### Create Rating
POST {{url}}/rating
Content-Type: application/json

{
    "rating": 5,
    "feedback": "Great session!",
    "gameName": "bulletspeel"
}

### Get Ratings by Page (limit 10 by page)
GET {{url}}/rating/1?game=bulletspeel

### Create Session
POST {{url}}/session
Content-Type: application/json

{
    "gameName": "cordel",
    "timespent": 120,
    "deaths": 3,
    "colorPicked": 2,
    "enemysKilled": 15,
    "gameFinished": true,
    "money": 100,
    "ammunation": 50,
    "items": true
}

### Get Session by Page (limit 10 by page)
GET {{url}}/session/1?game=bulletspeel
